#!/usr/bin/env python
'''tellfl.

Usage:
  tellfl CSV USER [--location LOCATION]
  tellfl install [--location LOCATION]
  tellfl --help
  tellfl --version

Arguments:
  CSV   The path to a .csv Oyster journey history report from TfL
  USER  The unique username to assciate the history to

Options:
  --location=LOCATION  The location of the tellfl install [default: /usr/local/tellfl]. # NOQA
  --help      Show this screen.
  --version   Show version.
'''
from docopt import docopt
from tellfl import tellfl

arguments = docopt(__doc__, version='tellfl 0.1')
if arguments['install']:
    tellfl.install(arguments['location'])
else:
    tellfl.run(arguments['USER'], arguments['CSV'], arguments['location'])
