#!/usr/bin/env python
'''tellfl.

Usage:
  tellfl install [--location LOCATION]
  tellfl register USER [--location LOCATION]
  tellfl add USER CSV [--location LOCATION]
  tellfl report USER [--html] [--location LOCATION]
  tellfl --help
  tellfl --version

Arguments:
  CSV   The path to a .csv Oyster journey history report from TfL
  USER  The unique username to assciate the history to

Options:
  --location LOCATION  The location of the tellfl install [default: /usr/local/tellfl]. # NOQA
  --html               Output the report as HTML, instead of plain text
  --help               Show this screen
  --version            Show version
'''
from docopt import docopt
from tellfl import tellfl

arguments = docopt(__doc__, version='tellfl 0.1')
try:
    if arguments['install']:
        tellfl.install(arguments['--location'])
    elif arguments['register']:
        tellfl.register(
            arguments['USER'],
            arguments['--location']
        )
    elif arguments['add']:
        tellfl.add(
            arguments['USER'],
            arguments['CSV'],
            arguments['--location']
        )
    elif arguments['report']:
        tellfl.report(
            arguments['USER'],
            arguments['--location'],
            arguments['--html']
        )
except Exception as e:
    print 'Something went wrong:', e
    import sys
    print sys.exc_info()[0]
